name: 测试最后一天执行

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: lastdat
      id: lastday
      run:
        lastday=$(date -d "+1 day" +%m) != $(date +%m)
        echo "::set-output name=islastday::$lastday"
    - name: printresult
        echo $steps.lastday.outputs.islastday

